name: Deploy Laravel to cPanel

on:
  push:
    branches: [ master ]  # Replace 'master' with your branch name if needed

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      # Step 1: Checkout the code
      - uses: actions/checkout@v3

      # Step 2: Setup PHP
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'

      # Step 3: Setup Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'

      # Step 4: Install Node Dependencies
      - name: Install Node Dependencies
        run: |
          npm install
          npm run build

      # Step 5: Install Composer Dependencies
      - name: Install Composer Dependencies
        run: |
          composer install --no-dev --optimize-autoloader

      # Step 6: Generate Laravel Environment
      - name: Setup Environment
        run: |
          cp .env.example .env
          php artisan key:generate --force
          php artisan config:clear
          php artisan cache:clear

      # Step 7: Prepare Deployment Directory
      - name: Prepare Deployment Files
        run: |
          mkdir -p deploy/demo
          cp -r app artisan bootstrap config database lang resources routes storage tests vendor composer.json composer.lock public .env deploy/demo/

      # Step 8: Install LFTP
      - name: Install LFTP
        run: sudo apt-get install -y lftp

      # Step 9: Deploy with LFTP
      - name: Deploy to cPanel with LFTP
        env:
          FTP_SERVER: ${{ secrets.FTP_SERVER }}
          FTP_USERNAME: ${{ secrets.FTP_USERNAME }}
          FTP_PASSWORD: ${{ secrets.FTP_PASSWORD }}
        run: |
          lftp -c
          set ftp:ssl-allow no;
          open -u $FTP_USERNAME,$FTP_PASSWORD $FTP_SERVER;
          mirror -R --delete --verbose ./deploy/demo/ /remote-folder/"
