name: Deploy Laravel to cPanel
on:
  push:
    branches: [ main ]  # Adjust this to your main branch name

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'

      - name: Install Composer Dependencies
        run: |
          composer install --no-dev --optimize-autoloader
          # Clear cache and optimize
          php artisan config:clear
          php artisan cache:clear
          php artisan package:discover --ansi

      - name: Copy .env
        run: php -r "file_exists('.env') || copy('.env.example', '.env');"

      - name: Generate Laravel Application Key
        run: php artisan key:generate --force

      - name: Directory Preparation
        run: |
          mkdir -p deploy/demo/demo.nopalcactus.co.ke
          cp -r app artisan bootstrap config database lang resources routes storage tests vendor composer.json composer.lock .env.example deploy/demo/
          cp -r public/* deploy/demo/demo.nopalcactus.co.ke/

      - name: FTP Deploy Laravel Files
        uses: SamKirkland/FTP-Deploy-Action@v4.3.4
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          local-dir: ./deploy/demo/
          server-dir: ./demo/

      - name: FTP Deploy Public Files
        uses: SamKirkland/FTP-Deploy-Action@v4.3.4
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          local-dir: ./deploy/demo.nopalcactus.co.ke/
          server-dir: ./demo.nopalcactus.co.ke/
